### PR TITLE
fix: Remove conditional attributes after the condition is unmatched

### LINKED ISSUE #56: Conditionals attributes are not removed after the condition is unmatched
### Problem

The following example is about `description`, but this happens with any conditional attribute (title, minimum, etc).

Given a form that asks for two fields `is_full_time` (yes/no) and `hours` (number). If yes is selected, then it shows a description warning about the maximum hours.

The JSON Schema is the following:

```json
{
  "properties": {
    "is_full_time": {
      "type": "string",
      "title": "Is full time",
      "oneOf": [{ "const": "yes", "title": "Yes" }, { "const": "no", "title": "No" }]
    },
    "hours": { "type": "number", "title": "Hours per day" }
  },
  "allOf": [
    {
      "if": {
        "properties": { "is_full_time": { "const": "yes" } },
        "required": ["is_full_time"]
      },
      "then": {
        "properties": {
          "hours": {
            "description": "We recommend no more than 8 hours."
          }
        }
      }
    }
  ]
}
```

Steps to reproduce:
1. In the [playground](https://json-schema-form.vercel.app/?path=/docs/playground--playground) add the schema above.
2. Select Yes, the description shows up.
3. Select No. The description should disappear but it remains 🐛 

image

For this scenario, a workaround could be to undo the value by set `description: ""` in the `else` statement, like this:
```
"else": {
  "properties": {
    "hours": {
      "description": ""
     }
   }
}
```

But this ain't possible for every attribute. For example, if you set `const: 10`, there's no way to "undo" it. Same for any other type of validation.

### PR DESCRIPTION
**Pull request by sandrina-p**
## Description

Fixes #56

How? When the fields get updated after parsing each conditional, compare the conditional attrs to the previous base field attrs. If an attr in the prev base is no longer present in the conditional, then remove it.

### CODE REVIEW

File: src/helpers.js [hunk 1]
```diff
@@ -12,6 +12,44 @@ import { processJSONLogicNode } from './jsonLogic';
...
+/**
+ *
+ * @param {*} finalField
+ * @param {*} branchAttrs
+ */
+function removeStaleAttrsFromField(field, latestAttrs) {
+  Object.keys(field).forEach((key) => {
+    if (
+      latestAttrs[key] === undefined &&
+      fieldJsfAttrsObj[key] === undefined // ignore these because they are internal
```
Comment (sandrina-p) [inline src/helpers.js:45]: note: In the original PR (https://github.com/remoteoss/json-schema-form/pull/52) it was created a list of attrs that can be removed. In this PR, I think it's safer to do it the other way around: create a list of fields that cannot be removed, which is basically every internal computed JSF attr (`fieldJsfAttrsObj`).

I still don't think this is the ideal solution and the real problem is somewhere earlier in the data flow.

But based on the urgency to unblock other features/consumers and the strong unit-tests, I'm comfortable with this solution.

File: src/tests/conditions.test.js [hunk 2]
```diff
@@ -56,3 +51,308 @@ it('Should allow check of a nested property in a conditional', () => {
...
+    // Changing to "No", it applies the base value again.
+    expect(handleValidation({ is_full_time: 'no' }).formErrors).toBeUndefined();
+    expect(fields[1].anything).toBe('info');
+
+    // Changing back to "Yes", it sets the attribute again
+    expect(handleValidation({ is_full_time: 'yes' }).formErrors).toBeUndefined();
+    expect(fields[1].anything).toBe('danger');
+  });
+
+  it('Keeps existing attributes in matches that dont change the attr', () => {
```
Comment (sandrina-p) [inline src/tests/conditions.test.js:249]: bug: Our internal Storybook tests spot this scenario as failing. I'm looking into a fix right now.

Comment (sandrina-p) [reply src/tests/conditions.test.js:249]: I think I cracked it, ready for review!

Change summary: We cannot compare the `conditionalAttrs` to the current`field` alone, we also need to compare it to the original field (the ones in the root).

File: src/helpers.js [hunk 3]
```diff
@@ -202,19 +237,19 @@ function updateField(field, requiredFields, node, formValues, logic, config) {
     field.isVisible = true;
   }
 
-  const updateValues = (fieldValues) =>
-    Object.entries(fieldValues).forEach(([key, value]) => {
-      // some values (eg "schema") are a function, so we need to call it here
+  const updateAttributes = (fieldAttrs) => {
```
Comment (sandrina-p) [inline src/helpers.js:240]: nit: I renamed it from `updateValues` because I thought it was about the field value (eg has_pet: "yes")

File: src/helpers.js [hunk 4]
```diff
@@ -226,36 +261,38 @@ function updateField(field, requiredFields, node, formValues, logic, config) {
...
   if (field.calculateConditionalProperties) {
-    const newFieldValues = field.calculateConditionalProperties({
+    const { rootFieldAttrs, newAttributes } = field.calculateConditionalProperties({
       isRequired: fieldIsRequired,
       conditionBranch: node,
       formValues,
     });
-    updateValues(newFieldValues);
+    updateAttributes(newAttributes, rootFieldAttrs);
+    removeConditionalStaleAttributes(field, newAttributes, rootFieldAttrs);
```
Comment (sandrina-p) [inline src/helpers.js:286]: note: In the first commit the `removeConditionalStaleAttributes` was inside `updateAttributes` so it would be called for every dynamic scenario (conditionals, custom validations, and computed attrs). But tha it caused other tests to fail, and I couldn't understand why in a short time.

As this bug is specifically focused on "leaked" attributes in conditionals, I decided to focus the solution only on that for now. I never saw bugs reported from the other dynamic scenarios, so... as they say "[if it ain't broke, don't fix it](https://en.wikipedia.org/wiki/wikt:if_it_ain%27t_broke,_don%27t_fix_it)." 

A conscious trade-off between between speed and excellence.

File: src/helpers.js [hunk 5]
```diff
@@ -226,36 +261,38 @@ function updateField(field, requiredFields, node, formValues, logic, config) {
...
   // If field has a calculateConditionalProperties closure, run it and update the field properties
   if (field.calculateConditionalProperties) {
-    const newFieldValues = field.calculateConditionalProperties({
+    const { rootFieldAttrs, newAttributes } = field.calculateConditionalProperties({
       isRequired: fieldIsRequired,
       conditionBranch: node,
       formValues,
     });
-    updateValues(newFieldValues);
+    updateAttributes(newAttributes, rootFieldAttrs);
```
Comment (remotecom) [inline src/helpers.js:285]: You're passing in `rootFieldAttrs` but as far as I can see, it's not used, right?

Comment (brennj) [inline src/helpers.js:285]: You're passing in `rootFieldAttrs` but as far as I can tell, its not used right?

**Review by brennj — COMMENTED** [review]
Just one small thing needs to be changed and its only a lint error. Otherwise, tests are fantastic and I'm so happy we have this now.

File: src/helpers.js (hunk 5 above)
Comment (sandrina-p) [reply src/helpers.js:285]: Ups, a tail from previous commits, removed!

File: src/helpers.js [hunk 6]
```diff
@@ -12,6 +12,41 @@ import { processJSONLogicNode } from './jsonLogic';
...
+ *
+ * @param {Object} field - Current field attributes
+ * @param {Object} conditionalAttrs - Attributes from the matched conditional
+ * @param {Object} rootAttrs - Original field attributes from the root.
+ */
+function removeConditionalStaleAttributes(field, conditionalAttrs, rootAttrs) {
+  Object.keys(field).forEach((key) => {
+    if (
+      conditionalAttrs[key] === undefined &&
+      rootAttrs[key] === undefined && // Don't remove attrs that were declared in the root field.
```
[the remark this answers is not in the document]
Comment (sandrina-p) [reply src/helpers.js:42]: Yes, also the `dynamicInternalJsfAttrsObj` (which is the opposite of your initial solution).

[the remark this answers is not in the document]
Comment (sandrina-p) [reply src/helpers.js:42]: > [@brennj] Just one small thing needs to be changed and its only a lint error. Otherwise, tests are fantastic and I'm so happy we have this now.

Cool! I'm gonna wait for the internal pipelines to be green before merging this one.

**Review by dilvane — COMMENTED** [review]
This is a fantastic fix! Thanks for this, until now, we were using the "workaround" to override the attribute like you showed in the playground, but with the "const" the need for this fix is more visible!

File: src/calculateConditionalProperties.js [hunk 7]
```diff
@@ -69,14 +69,19 @@ function rebuildFieldset(fields, property) {
...
  * @param {Object} params.config - Form configuration
  *
  * @returns {Function} A function that calculates conditional properties
  */
 export function calculateConditionalProperties({ fieldParams, customProperties, logic, config }) {
+  /**
+   * @typedef {calculateConditionalPropertiesReturn}
+   * @property {rootFieldAttrs} x - The field attributes from the first render (root)
+   * @property {newAttributes} y - Attributes from the matched conditional
+   */
```
[the remark this answers is not in the document]
Comment (sandrina-p) [reply src/calculateConditionalProperties.js:84]: Ups, fixed! I also removed the dev version for final approval

**Review by brennj — APPROVED** [review]

**Comment by sandrina-p** [comment]
`@remoteoss/json-schema-form@0.7.3-beta.0` released 📦
